#!/usr/bin/env node

// Generated by LiveScript 1.2.0
(function(){
  var path, fs, tweak, spit, slurp;
  path = require('path');
  fs = require('fs');
  tweak = function(file, ext){
    return path.basename(file).concat(ext);
  };
  spit = function(file, content){
    return fs.writeFile(file, content, function(err){
      if (err) {
        throw "error writing: " + file;
      }
      return console.log("wrote to " + file);
    });
  };
  slurp = function(file){
    var content;
    readContent(file, function(err, data){
      var content;
      return content = data;
    });
    return content;
  };
  function readContent(file, cb){
    fs.readFile(file, function(err, data){
      if (err) {
        cb(err);
      }
      return cb(null, data);
    });
  }
  module.exports = {
    spit: spit,
    slurp: slurp,
    tweak: tweak
  };
}).call(this);
